-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public._prisma_migrations (
  id character varying NOT NULL,
  checksum character varying NOT NULL,
  finished_at timestamp with time zone,
  migration_name character varying NOT NULL,
  logs text,
  rolled_back_at timestamp with time zone,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_steps_count integer NOT NULL DEFAULT 0,
  CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tenants (
  id text NOT NULL,
  razaoSocial text NOT NULL,
  nomeFantasia text NOT NULL,
  cnpj text NOT NULL,
  email text NOT NULL,
  telefone text,
  plano USER-DEFINED NOT NULL DEFAULT 'BASICO'::"Plano",
  status USER-DEFINED NOT NULL DEFAULT 'ATIVO'::"StatusTenant",
  geofenceLat double precision,
  geofenceLng double precision,
  geofenceRaio integer NOT NULL DEFAULT 200,
  fotoObrigatoria boolean NOT NULL DEFAULT true,
  geofenceAtivo boolean NOT NULL DEFAULT false,
  toleranciaMinutos integer NOT NULL DEFAULT 5,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  trabalhoMinimoAntesSaidaMinutos integer NOT NULL DEFAULT 30,
  intervaloMinimoAlmocoMinutos integer NOT NULL DEFAULT 30,
  permitirTotem boolean NOT NULL DEFAULT true,
  permitirMeuPonto boolean NOT NULL DEFAULT true,
  contractStartDate timestamp without time zone,
  contractEndDate timestamp without time zone,
  periodoContrato USER-DEFINED,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.usuarios (
  id text NOT NULL,
  tenantId text NOT NULL,
  nome text NOT NULL,
  email text NOT NULL,
  pinHash text NOT NULL,
  cargo text,
  departamento text,
  role USER-DEFINED NOT NULL DEFAULT 'COLABORADOR'::"Role",
  ativo boolean NOT NULL DEFAULT true,
  fotoPerfil text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  pinEncrypted text,
  localRegistroId text,
  senhaHash text,
  passwordResetToken text,
  passwordResetExpires timestamp without time zone,
  dataAdmissao timestamp without time zone,
  dataDemissao timestamp without time zone,
  assinaturaPadraoDataUrl text,
  assinaturaPadraoStrokes jsonb,
  assinaturaPadraoAtualizadaEm timestamp without time zone,
  isentoGeofence boolean NOT NULL DEFAULT false,
  cpf text,
  pis text,
  matricula text,
  tipoContrato USER-DEFINED NOT NULL DEFAULT 'CLT'::"TipoContrato",
  salarioBase numeric,
  categoriaProfissional text,
  dependentesIrrf integer NOT NULL DEFAULT 0,
  contaBanco text,
  contaAgencia text,
  contaNumero text,
  contaTipo USER-DEFINED,
  CONSTRAINT usuarios_pkey PRIMARY KEY (id),
  CONSTRAINT usuarios_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT usuarios_localRegistroId_fkey FOREIGN KEY (localRegistroId) REFERENCES public.locais_registro(id)
);
CREATE TABLE public.registros_ponto (
  id text NOT NULL,
  tenantId text NOT NULL,
  usuarioId text NOT NULL,
  tipo USER-DEFINED NOT NULL,
  dataHora timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  latitude double precision,
  longitude double precision,
  dentroGeofence boolean,
  fotoUrl text,
  fotoKey text,
  deviceId text,
  ipHash text,
  userAgent text,
  validado boolean NOT NULL DEFAULT true,
  origem USER-DEFINED NOT NULL DEFAULT 'TOTEM'::"OrigemPonto",
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deletedAt timestamp without time zone,
  deletedById text,
  deletedMotivo text,
  clientRequestId text,
  CONSTRAINT registros_ponto_pkey PRIMARY KEY (id),
  CONSTRAINT registros_ponto_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT registros_ponto_usuarioId_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id),
  CONSTRAINT registros_ponto_deletedById_fkey FOREIGN KEY (deletedById) REFERENCES public.usuarios(id)
);
CREATE TABLE public.escalas (
  id text NOT NULL,
  tenantId text NOT NULL,
  usuarioId text NOT NULL,
  nome text NOT NULL,
  horaInicio text NOT NULL,
  horaFim text NOT NULL,
  diasSemana ARRAY,
  cargaHorariaDiaria double precision NOT NULL DEFAULT 8,
  intervaloMinutos integer NOT NULL DEFAULT 60,
  ativo boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  horaRetornoAlmoco text,
  horaSaidaAlmoco text,
  CONSTRAINT escalas_pkey PRIMARY KEY (id),
  CONSTRAINT escalas_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT escalas_usuarioId_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.ajustes_ponto (
  id text NOT NULL,
  tenantId text NOT NULL,
  registroId text NOT NULL,
  adminId text NOT NULL,
  dataHoraOriginal timestamp without time zone NOT NULL,
  dataHoraNova timestamp without time zone NOT NULL,
  motivo text NOT NULL,
  aprovado boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ajustes_ponto_pkey PRIMARY KEY (id),
  CONSTRAINT ajustes_ponto_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT ajustes_ponto_registroId_fkey FOREIGN KEY (registroId) REFERENCES public.registros_ponto(id),
  CONSTRAINT ajustes_ponto_adminId_fkey FOREIGN KEY (adminId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.super_admins (
  id text NOT NULL,
  email text NOT NULL,
  senhaHash text NOT NULL,
  nome text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  passwordResetToken text,
  passwordResetExpires timestamp without time zone,
  CONSTRAINT super_admins_pkey PRIMARY KEY (id)
);
CREATE TABLE public.locais_registro (
  id text NOT NULL,
  tenantId text NOT NULL,
  nome text NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  raioMetros integer NOT NULL DEFAULT 200,
  ativo boolean NOT NULL DEFAULT true,
  ordem integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT locais_registro_pkey PRIMARY KEY (id),
  CONSTRAINT locais_registro_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.comprovantes_ausencia (
  id text NOT NULL,
  tenantId text NOT NULL,
  usuarioId text NOT NULL,
  dataReferencia text NOT NULL,
  dataFim text,
  descricao text,
  tipoArquivo text NOT NULL,
  arquivoKey text,
  arquivoUrl text,
  mimeType text,
  nomeArquivoOriginal text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDENTE'::"StatusComprovante",
  observacaoAdmin text,
  respondidoPorId text,
  respondidoEm timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT comprovantes_ausencia_pkey PRIMARY KEY (id),
  CONSTRAINT comprovantes_ausencia_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT comprovantes_ausencia_usuarioId_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id),
  CONSTRAINT comprovantes_ausencia_respondidoPorId_fkey FOREIGN KEY (respondidoPorId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.solicitacoes_ajuste_ponto (
  id text NOT NULL,
  tenantId text NOT NULL,
  usuarioId text NOT NULL,
  dia text NOT NULL,
  tipo USER-DEFINED NOT NULL,
  dataHoraSugerida timestamp without time zone,
  justificativa text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDENTE'::"StatusSolicitacaoAjustePonto",
  respondidoPorId text,
  respondidoEm timestamp without time zone,
  respostaAdmin text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT solicitacoes_ajuste_ponto_pkey PRIMARY KEY (id),
  CONSTRAINT solicitacoes_ajuste_ponto_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT solicitacoes_ajuste_ponto_usuarioId_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id),
  CONSTRAINT solicitacoes_ajuste_ponto_respondidoPorId_fkey FOREIGN KEY (respondidoPorId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.feriados (
  id text NOT NULL,
  tenantId text NOT NULL,
  data text NOT NULL,
  nome text NOT NULL,
  suspendeExpediente boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT feriados_pkey PRIMARY KEY (id),
  CONSTRAINT feriados_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.ferias (
  id text NOT NULL,
  tenantId text NOT NULL,
  usuarioId text NOT NULL,
  dataInicio text NOT NULL,
  dataFim text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDENTE'::"StatusFerias",
  observacao text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  respondidoEm timestamp without time zone,
  respostaAdmin text,
  CONSTRAINT ferias_pkey PRIMARY KEY (id),
  CONSTRAINT ferias_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT ferias_usuarioId_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.espelho_fechamentos (
  id text NOT NULL,
  tenantId text NOT NULL,
  usuarioId text NOT NULL,
  mes integer NOT NULL,
  ano integer NOT NULL,
  espelhoHash text,
  aprovadoEm timestamp with time zone DEFAULT now(),
  assinaturaDataUrl text,
  assinaturaStrokes jsonb,
  ipHash text,
  userAgent text,
  deviceId text,
  createdAt timestamp with time zone NOT NULL DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'ASSINADO'::"StatusEspelhoFechamento",
  solicitadoPorId text,
  solicitadoEm timestamp with time zone,
  CONSTRAINT espelho_fechamentos_pkey PRIMARY KEY (id),
  CONSTRAINT espelho_fechamentos_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT espelho_fechamentos_usuarioId_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id),
  CONSTRAINT espelho_fechamentos_solicitadoPorId_fkey FOREIGN KEY (solicitadoPorId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.tenant_features (
  tenantId text NOT NULL,
  payrollModuleEnabled boolean NOT NULL DEFAULT false,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tenant_features_pkey PRIMARY KEY (tenantId),
  CONSTRAINT tenant_features_tenantid_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.folha_config (
  tenantId text NOT NULL,
  modoBancoHoras USER-DEFINED NOT NULL DEFAULT 'COMPENSAR'::"ModoBancoHoras",
  heDiaUtilPercent integer NOT NULL DEFAULT 50,
  heDomingoFeriadoPercent integer NOT NULL DEFAULT 100,
  adicionalNoturnoPercent integer NOT NULL DEFAULT 20,
  toleranciaAtrasoMin integer,
  pagarDSR boolean NOT NULL DEFAULT true,
  permitirFolhaSemAssinatura boolean NOT NULL DEFAULT false,
  tabelasVersao text,
  tabelasSnapshot jsonb,
  bancoCodigo text,
  bancoAgencia text,
  bancoConta text,
  bancoConvenio text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT folha_config_pkey PRIMARY KEY (tenantId),
  CONSTRAINT folha_config_tenantid_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.folha_runs (
  id text NOT NULL,
  tenantId text NOT NULL,
  mes integer NOT NULL,
  ano integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'RASCUNHO'::"StatusFolhaRun",
  calculadaEm timestamp without time zone,
  fechadaEm timestamp without time zone,
  fechadaPorId text,
  bloqueadaPorPendencias jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT folha_runs_pkey PRIMARY KEY (id),
  CONSTRAINT folha_runs_tenantid_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT folha_runs_fechadaporid_fkey FOREIGN KEY (fechadaPorId) REFERENCES public.usuarios(id)
);
CREATE TABLE public.holerites (
  id text NOT NULL,
  folhaRunId text NOT NULL,
  usuarioId text NOT NULL,
  proventos jsonb NOT NULL,
  descontos jsonb NOT NULL,
  bases jsonb NOT NULL,
  liquido numeric NOT NULL,
  pdfKey text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT holerites_pkey PRIMARY KEY (id),
  CONSTRAINT holerites_folharunid_fkey FOREIGN KEY (folhaRunId) REFERENCES public.folha_runs(id),
  CONSTRAINT holerites_usuarioid_fkey FOREIGN KEY (usuarioId) REFERENCES public.usuarios(id)
);